[package]
name = "joy"
version = "0.1.0"
authors = ["yamakaky"]
edition = "2018"

[workspace]
members = [
    "joycon-sys",
]

[dependencies]
anyhow = "1.0"
enigo = "0.0.14"
env_logger = "0.7"
hidapi = "1.2"
image = { version = "0.23", default-features = false }
joycon-sys = { path = "joycon-sys" }
iced_wgpu = { git = "https://github.com/hecrj/iced"}
iced_winit = { git = "https://github.com/hecrj/iced"}
futures = "0.3"
vk-shader-macros = "0.2"
cgmath = { version = "0.17", default-features = false }
bytemuck = "1.2"