[package]
name = "joy"
version = "0.1.0"
authors = ["yamakaky"]
edition = "2018"

[workspace]
members = [
    "joycon-sys",
]

[dependencies]
anyhow = "1.0"
enigo = "0.0.14"
image = { version = "0.23", features = ["png"], default_features = false }
hidapi = "1.2"
joycon-sys = { path = "joycon-sys" }