[workspace]
members = [
    "dualshock-sys",
    "dualshock",
    "hid-gamepad",
    "hid-gamepad-sys",
    "joycon-sys",
    "joycon",
    # removed for huge number of deps
    #"joy-infrared",
    "joy-music",
    "joytk",
    "gyromouse",
]
