[workspace]
members = [
    "bluetooth-relay",
    "dualshock-sys",
    "dualshock",
    "hid-gamepad",
    "hid-gamepad-sys",
    "joycon-sys",
    "joycon",
    "joy-infrared",
    "joy-music",
    "joytk",
    "gyromouse",
]
