[package]
name = "gyromouse"
version = "0.1.0"
authors = ["Mikaël Fourrier <mikael.fourrier@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
cgmath = "0.17.0"
enigo = "0.0.14"
enum-map = "0.6.4"
hid-gamepad = { path = "../hid-gamepad" }
joycon = { path = "../joycon" }
nom = "6.0.1"
