name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [linux, windows, macos]
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.local/share/cargo
            target
          key: ${{ runner.os }}-cargo-v1-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 🔨 Build gyromouse
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --bin gyromouse
      - name: 🔨 Rename binaries
        if: matrix.platform != 'windows'
        env:
          OS: ${{matrix.platform}}
        run: |
          cp target/release/gyromouse target/release/gyromouse-$OS

      - name: ☁️ Upload gyromouse
        uses: actions/upload-artifact@v2
        with:
          name: client
          if-no-files-found: error
          path: |
            target/release/gyromouse-linux
            target/release/gyromouse-macos
            target/release/gyromouse.exe
